[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/api/status"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[nixpacks]
install-cmds = [
  "apt-get update",
  "apt-get install -y ffmpeg python3 python3-pip curl"
]